### ISSUE TITLE
Add Nginx to docker to support complicated web config

### ISSUE THREAD

**Issue by snowme34** [CTrando/UCSD-Planner-Helper#34]
Edit `docker-compose.yml` to include nginx container listening to port 80 and port 443.

Note that the container of letsencrypt should not be included here since people don't want to generate/renew ssl key each time when `docker-compose up`. It should be renewed using `crontab`

When we decided to use letsencrypt, we can add the necessary conf. The ssl of letsencrypt needs to be verified using the domain name so currently there is not way for me to do this.

Also we might be able to "hide" the ports of backend and frontend containers.

(For Nginx, I used user `nginx` instead of `www-data`)

**Comment by snowme34** [comment]
I tested the Nginx server locally. The Nginx itself works but I don't know if "exposing" the port for frontend only works for our app.

**Comment by CTrando** [comment]
Alright! I'll take a look at this. @dmhacker Can you look too?

**Comment by dmhacker** [comment]
@CTrando @snowme34 

It looks pretty good for a start. Maybe consider see if you can compile the React files and then get the nginx container to serve them rather than using the standalone React server like we do now. Right now, the nginx container just sits there as an unconnected web server, so it's not really doing a whole lot. In short, see if you can:

1. Compile React scripts (`npm run build` instead of `npm start`).
2. Remap nginx port internally from sdschedule-web:80 to localhost:3000. I usually like to have development servers running on port 3000-5000, not 80.
3. Get nginx to serve the files that React has compiled (nginx is pretty good at static file hosting, so this shouldn't be an issue). This is where things might get a big tricky. My approach would be to unify the sdschedule-web and sdschedule-frontend containers and have nginx and node on both. Compile the React scripts and then get
nginx to serve the built files. I'll leave this up to you though; if you can find a way to keep the nginx and node containers separate, all the better.

Also, I see you tried to merge changes to master into your branch, which may actually causes some issues. However, we can cherry pick changes, so it's not a big deal. In the future, note that doing that isn't really necessary.1

**Comment by CTrando** [comment]
We want to use `yarn run build` instead of `npm run build` due to the fact that yarn doesn't have issues using forks of npm libraries like npm does.

**Comment by snowme34** [comment]
Thank you for your suggestions.

I thought we are using nginx only for reverse proxy and https. I'll look into it

**Comment by CTrando** [comment]
Yeah you're right, I goofed on that - just saw npm and thought yarn. The backend is only going to be sending out http data and there is no server side rendering involved. Sorry about that and good luck on finals!

**Comment by snowme34** [comment]
I created 2 separated docker-compose files for dev and prod environments. 

The old `docker-install.sh` and `docker-compose.yml` are now renamed to be legacy.

I tested the dev one but failed to test the prod one since the `yarn run build` will create a web page that can only be properly displayed in given domain name .

```
sdschedule-frontend    | The project was built assuming it is hosted at http://sdschedule.com/.
sdschedule-frontend    | You can control this with the homepage field in your package.json.
```

Something to note:
1. Since Nginx is intended to use in production environment and it makes no sense to debug our app using `yarn run build`, there is no need to make Nginx work on port for development (or even use Nginx for development, other than port forwarding if necessary)
2. The fronted container will exit automatically after building and copying the files to a docker volume. There would be no need to expose the 3000 port for it anymore

**Comment by CTrando** [comment]
Interesting. You want to meet in the next few days to discuss this?

**Comment by snowme34** [comment]
Perhaps next week?

**Comment by snowme34** [comment]
To make it easier for other teammates to understand:

* The `Nginx` container acts as the http service for the production environment, not doing anything but serving static files yet
* The docker compose file for production environment will run the front-end container to compile the files for React front end, as suggested by @dmhacker, and send those files to a docker volume shared with the `Nginx` container
* Afterwards, the front-end container will exit. Only the `Nginx` and the back-end container will be running
* For development environment, I think it is unnecessary to use `Nginx`

`Nginx` was chosen since it is known for its performance and lightweight

For load balance, we can use `Nginx` directly or try to do something with `docker`?
