### ISSUE TITLE
Redesign the website

### ISSUE THREAD

**Issue by CTrando** [CTrando/UCSD-Planner-Helper#40]
Make the website more easy to use and intuitive and make it scalable for future features such as CAPES integration and course catalog integration.

**Comment by coraxyc** [comment]
Prototype that only fits a MacBook pro screen right now, if you set it to full screen. If you're using Windows or any other screen size you might have to scroll around:

https://www.figma.com/proto/BojOckmBQm0d7V1zu6y9FEHB/UCSD-Schedule-Planner?node-id=0%3A1&scaling=min-zoom

Can I make a #design channel on Slack and post this for thoughts from everyone?

**Comment by CTrando** [comment]
Yeah, sure do whatever you need to do. You have pretty much full reign over design right now, if you need anything ask me, but basically take that as you have permission to do whatever as long as it benefits someone and doesn't hurt others.

**Comment by CTrando** [comment]
Also, I see you are somewhat trying to maintain the style of the previous - don't feel like you're restrained by that, I'm completely open to a full redesign so you don't need to maintain any elements of the previous design.

**Comment by snowme34** [comment]
Good job! Hope I knew JS enough to contribute.

## Some unexpected behavior

* TBA means Nothing!

![image](https://user-images.githubusercontent.com/13925662/51495728-2f62eb80-1d72-11e9-8bb0-2ccf89393dd9.png)

* Strange Cancel:

![strange-cancel](https://user-images.githubusercontent.com/13925662/51495741-37bb2680-1d72-11e9-9ce0-bb242142e071.gif)

* Press TAB will send 2 requests

![tab-duplicated-request](https://user-images.githubusercontent.com/13925662/51495770-53263180-1d72-11e9-860d-83a6b29dc3f4.gif)

![tab-duplicated-request](https://user-images.githubusercontent.com/13925662/51495778-59b4a900-1d72-11e9-85bf-446a626450d0.png)

* Strange highlight for some screen width

![uncompleted-highlight](https://user-images.githubusercontent.com/13925662/51495807-6e913c80-1d72-11e9-8aca-7206a0e75b63.png)

* Don't quite understand the underneath logic for mutiple "Instructor Preferences"

## Some modest proposals for functionality:

1. Add undo functionality
2. Hide "CAPE" if not planning to support yet
3. Click on course in calendar will also enable highlight
4. User can move the vertical bar between calendar and course list (like drag or a drawer)
5. Clear all button
6. Add warning if "TBA" (currently only shows a blank calendar)

It feels like this "Edit" button should be called like "Regenerate" since user does not need to click it to edit.

![image](https://user-images.githubusercontent.com/13925662/51495013-ac409600-1d6f-11e9-9ad4-a761612dbce9.png)


## Some words about design

I don't quite understand the meaning of the light grey shadow behind the "course block". Is it representing some features?

![image](https://user-images.githubusercontent.com/13925662/51494727-94b4dd80-1d6e-11e9-97ce-d1560dafacdf.png)

Also the brown background of Instructor's name is a little bit of scary.

![image](https://user-images.githubusercontent.com/13925662/51494954-77344380-1d6f-11e9-9336-cca43e4f1810.png)

## Conclusion

Sort of confused with the text in the top bar: do they represent some good wishes?

![image](https://user-images.githubusercontent.com/13925662/51496176-9e8d0f80-1d73-11e9-8a7f-6a71e546be7a.png)


Look forward to the returning of the multiple-version calendar! With that feature available, current app will be impressive!

**Comment by CTrando** [comment]
Closed with f38495b9c1d041ed40b34f33342bd084c1016293, I will make your suggestions into other issues.
